import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import API from '../services/api';
import { Award, Download, ShieldCheck, HelpCircle } from 'lucide-react';

const MyCertificates = () => {
  const { user } = useAuth();
  const [certificates, setCertificates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [downloadingId, setDownloadingId] = useState(null);

  useEffect(() => {
    const fetchCertificates = async () => {
      if (!user) return;
      try {
        const studentId = user.id || user._id;
        const response = await API.get(`/api/certificate/${studentId}`);
        setCertificates(response.data);
      } catch (err) {
        setError('Failed to fetch certificates.');
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchCertificates();
  }, [user]);

  const handleDownload = async (cert) => {
    setDownloadingId(cert._id);
    try {
      const response = await API.get(`/api/certificate/download/${cert._id}`, {
        responseType: 'blob',
      });
      
      const file = new Blob([response.data], { type: 'application/pdf' });
      const fileURL = URL.createObjectURL(file);
      const pdfWindow = window.open();
      if (pdfWindow) {
        pdfWindow.location.href = fileURL;
      } else {
        // Fallback file download link
        const link = document.createElement('a');
        link.href = fileURL;
        link.setAttribute('download', `Certificate_${cert.eventId.title.replace(/\s+/g, '_')}.pdf`);
        document.body.appendChild(link);
        link.click();
        link.remove();
      }
    } catch (err) {
      alert('Error downloading certificate. Please try again.');
      console.error(err);
    } finally {
      setDownloadingId(null);
    }
  };

  if (!user) {
    return <div className="text-center py-10 font-display text-maroon">Please log in to view certificates.</div>;
  }

  return (
    <div className="max-w-4xl mx-auto px-4 py-8 sm:px-6 bg-white min-h-screen">
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-display font-bold text-maroon">My Certificates</h1>
          <p className="text-black opacity-80 mt-1">Download and share your official college event participation and merit achievements.</p>
        </div>

        {error && (
          <div className="p-3 bg-lightgray/10 border border-maroon text-maroon text-sm font-semibold rounded-md">
            {error}
          </div>
        )}

        {loading ? (
          <div className="text-center py-10 font-display text-maroon">Loading certificates...</div>
        ) : certificates.length === 0 ? (
          <div className="border border-lightgray border-dashed rounded-lg p-12 text-center space-y-4">
            <Award className="h-12 w-12 text-maroon mx-auto opacity-40" />
            <p className="text-black opacity-80 font-medium">No certificates have been issued to you yet.</p>
            <p className="text-xs text-black opacity-60">
              Certificates are generated by administrators after events are completed and your attendance is marked as present.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {certificates.map((cert) => {
              const event = cert.eventId;
              if (!event) return null;

              const isMerit = cert.certificateType === 'merit';

              return (
                <div
                  key={cert._id}
                  className={`border rounded-lg bg-white p-6 flex flex-col justify-between hover:shadow-sm transition-shadow ${
                    isMerit ? 'border-maroon' : 'border-lightgray'
                  }`}
                >
                  <div className="space-y-3">
                    <div className="flex justify-between items-start">
                      <span
                        className={`px-3 py-1 text-[10px] font-bold rounded uppercase tracking-wider ${
                          isMerit
                            ? 'bg-maroon text-white'
                            : 'border border-maroon text-maroon'
                        }`}
                      >
                        {isMerit ? `Merit - ${cert.position || 'Winner'}` : 'Participation'}
                      </span>
                      <ShieldCheck className="h-5 w-5 text-maroon" title="Verified Credential" />
                    </div>

                    <h3 className="text-xl font-display font-bold text-maroon pt-1">{event.title}</h3>
                    <p className="text-xs text-black opacity-75 capitalize">{event.category} Event</p>
                    
                    <div className="text-xs text-black opacity-60 space-y-1">
                      <p>Date: {new Date(event.date).toLocaleDateString()}</p>
                      <p className="truncate">Cert ID: {cert.certificateId}</p>
                    </div>
                  </div>

                  <div className="mt-6 pt-4 border-t border-lightgray">
                    <button
                      onClick={() => handleDownload(cert)}
                      disabled={downloadingId === cert._id}
                      className="w-full py-2 bg-maroon text-white text-sm font-semibold rounded hover:opacity-90 transition-opacity flex items-center justify-center space-x-2 disabled:opacity-50"
                    >
                      <Download className="h-4 w-4" />
                      <span>{downloadingId === cert._id ? 'Generating...' : 'Download Certificate (PDF)'}</span>
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};

export default MyCertificates;
